version: "3"
services:
  node:
    image: node:20.11.0
    volumes:
      - type: bind
        source: ./portfolio-front
        target: /usr/src/app
    working_dir: /usr/src/app
    ports:
     - '3000:3000'
    environment:
      HOST: 0.0.0.0
