export default {
  "plugins": [
    "stylelint-scss",
    "stylelint-order",
  ],
  "rules": {
    "alpha-value-notation": "number",
    "annotation-no-unknown": true,
    "at-rule-empty-line-before": null,
    "at-rule-no-unknown": true,
    "block-no-empty": true,
    "color-function-notation": "modern",
    "color-hex-length": "long",
    "color-no-invalid-hex": true,
    "comment-empty-line-before": [
      "always",
      {
        "except": ["first-nested"]
      }
    ],
    "comment-no-empty": null,
    "comment-whitespace-inside": "always",
    "custom-property-no-missing-var-function": true,
    "declaration-block-no-duplicate-properties": true,
    "declaration-block-no-redundant-longhand-properties": [
      true,
      {
        "severity": "warning"
      },
      {
        "ignoreShorthands": ["/flex/", "/grid/", "/padding/"]
      }
    ],
    "declaration-block-no-shorthand-property-overrides": true,
    "declaration-block-single-line-max-declarations": 1,
    "declaration-empty-line-before": "never",
    "declaration-no-important": [
      true, {
        "severity": "warning"
      }
    ],
    "font-family-name-quotes": [
      "always-unless-keyword",
      {
        "severity": "warning"
      }
    ],
    "font-family-no-duplicate-names": true,
    "font-family-no-missing-generic-family-keyword": [
      true,
      {
        "severity": "warning"
      }
    ],
    "font-weight-notation": "numeric",
    "function-calc-no-unspaced-operator": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-name-case": "lower",
    "function-no-unknown": null,
    "function-url-no-scheme-relative": true,
    "function-url-quotes": [
      "always",
      {
        "severity": "warning"
      }
    ],
    "hue-degree-notation": "angle",
    "import-notation": "string",
    "keyframe-block-no-duplicate-selectors": true,
    "keyframe-declaration-no-important": true,
    "keyframe-selector-notation": "percentage-unless-within-keyword-only-block",
    "length-zero-no-unit": true,
    "media-feature-name-no-unknown": true,
    "media-feature-range-notation": null,
    "named-grid-areas-no-invalid": true,
    "no-descending-specificity": [
      true,
      {
        "severity": "warning"
      }
    ],
    "no-duplicate-at-import-rules": true,
    "no-duplicate-selectors": null,
    "no-empty-source": true,
    "no-invalid-double-slash-comments": true,
    "no-invalid-position-at-import-rule": [
      true,
      {
        ignoreAtRules: ["use", "forward"],
      },
    ],
    "no-irregular-whitespace": true,
    "no-unknown-animations": true,
    "number-max-precision": 6,
    "property-no-unknown": [
      true,
      {
        "checkPrefixed": true,
        "severity": "warning"
      }
    ],
    "rule-empty-line-before": [
      "always",
      {
        "ignore": [
          "first-nested",
          "after-comment"
        ]
      }
    ],
    "selector-not-notation": "simple",
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-element-colon-notation": "double",
    "selector-pseudo-element-no-unknown": true,
    "selector-type-case": [
      "lower",
      {
        "severity": "warning"
      }
    ],
    "selector-type-no-unknown": true,
    "shorthand-property-no-redundant-values": true,
    "string-no-newline": true,
    "unit-no-unknown": true,
    "value-keyword-case": "lower",
    "value-no-vendor-prefix": true,
    // Order
    "order/order": [
      "at-rules",
      "custom-properties",
      "dollar-variables",
      "declarations",
      "rules",
      {
        "type": "at-rule",
        "hasBlock": true,
      },
    ],
    "order/properties-order": [
      {
        "emptyLineBefore": "never",
        "noEmptyLineBetween": false,
        "properties": [
          // Specials
          "all",
          "content",
          // Position
          "position",
          "top",
          "right",
          "bottom",
          "left",
          "inset",
          "inset-block",
          "inset-block-end",
          "inset-block-start",
          "inset-inline",
          "inset-inline-end",
          "inset-inline-start",
          "z-index",
          // Display & Box model & Layout
          "box-sizing",
          "clear",
          "clip",
          "clip-path",
          "clip-rule",
          "display",
          "flex",
          "flex-basis",
          "flex-direction",
          "flex-flow",
          "flex-grow",
          "flex-shrink",
          "flex-wrap",
          "float",
          "gap",
          "grid",
          "grid-area",
          "grid-auto-columns",
          "grid-auto-flow",
          "grid-auto-rows",
          "grid-column",
          "grid-column-end",
          "grid-column-start",
          "grid-row",
          "grid-row-end",
          "grid-row-start",
          "grid-template",
          "grid-template-areas",
          "grid-template-columns",
          "grid-template-rows",
          "align-content",
          "align-items",
          "align-self",
          "justify-content",
          "justify-items",
          "justify-self",
          "margin",
          "margin-block-start",
          "margin-block-end",
          "margin-inline-start",
          "margin-inline-end",
          "margin-top",
          "margin-right",
          "margin-bottom",
          "margin-left",
          "padding",
          "padding-block-end",
          "padding-block-start",
          "padding-inline-end",
          "padding-inline-start",
          "padding-top",
          "padding-right",
          "padding-bottom",
          "padding-left",
          "width",
          "min-block-size",
          "max-block-size",
          "min-width",
          "max-width",
          "height",
          "min-height",
          "max-height",
          "min-inline-size",
          "max-inline-size",
          "order",
          "overflow",
          "overflow-anchor",
          "overflow-clip-margin",
          "overflow-wrap",
          "overflow-x",
          "overflow-y",
          "visibility",
          "zoom",
          // Visual style
          "backdrop-filter",
          "background",
          "background-attachment",
          "background-blend-mode",
          "background-clip",
          "background-color",
          "background-image",
          "background-origin",
          "background-position",
          "background-repeat",
          "background-size",
          "border",
          "border-radius",
          "border-block-end-color",
          "border-block-end-style",
          "border-block-end-width",
          "border-block-start-color",
          "border-block-start-style",
          "border-block-start-width",
          "border-inline-end-color",
          "border-inline-end-style",
          "border-inline-end-width",
          "border-inline-start-color",
          "border-inline-start-style",
          "border-inline-start-width",
          "border-top-color",
          "border-top-left-radius",
          "border-top-right-radius",
          "border-top-style",
          "border-top-width",
          "border-right-color",
          "border-right-style",
          "border-right-width",
          "border-bottom-color",
          "border-bottom-left-radius",
          "border-bottom-right-radius",
          "border-bottom-style",
          "border-bottom-width",
          "border-left-color",
          "border-left-style",
          "border-left-width",
          "border-collapse",
          "border-start-end-radius",
          "border-start-start-radius",
          "border-end-end-radius",
          "border-end-start-radius",
          "border-image-outset",
          "border-image-repeat",
          "border-image-slice",
          "border-image-source",
          "border-image-width",
          "box-shadow",
          "color-interpolation",
          "color-interpolation-filters",
          "color-rendering",
          "filter",
          "opacity",
          "outline",
          "outline-color",
          "outline-offset",
          "outline-style",
          "outline-width",
          "perspective",
          "perspective-origin",
          "transform",
          "transform-box",
          "transform-origin",
          "transform-style",
          // Typography
          "font",
          "font-family",
          "font-kerning",
          "font-optical-sizing",
          "font-palette",
          "font-size",
          "font-stretch",
          "font-style",
          "font-synthesis-small-caps",
          "font-synthesis-style",
          "font-synthesis-weight",
          "font-variant",
          "font-variant-alternates",
          "font-variant-caps",
          "font-variant-east-asian",
          "font-variant-ligatures",
          "font-variant-numeric",
          "font-weight",
          "color",
          "letter-spacing",
          "line-break",
          "line-height",
          "list-style-image",
          "list-style-position",
          "list-style-type",
          "text-align",
          "text-align-last",
          "text-anchor",
          "text-decoration",
          "text-decoration-color",
          "text-decoration-line",
          "text-decoration-skip-ink",
          "text-decoration-style",
          "text-emphasis-color",
          "text-emphasis-position",
          "text-emphasis-style",
          "text-indent",
          "text-overflow",
          "text-rendering",
          "text-shadow",
          "text-size-adjust",
          "text-transform",
          "text-underline-position",
          "white-space",
          "word-spacing",
          // Misc
          "accent-color",
          "alignment-baseline",
          "animation",
          "animation-composition",
          "animation-delay",
          "animation-direction",
          "animation-duration",
          "animation-fill-mode",
          "animation-iteration-count",
          "animation-name",
          "animation-play-state",
          "animation-timing-function",
          "app-region",
          "appearance",
          "backface-visibility",
          "baseline-shift",
          "baseline-source",
          "block-size",
          "break-after",
          "break-before",
          "break-inside",
          "buffered-rendering",
          "caption-side",
          "caret-color",
          "column-count",
          "column-gap",
          "column-rule-color",
          "column-rule-style",
          "column-rule-width",
          "column-span",
          "column-width",
          "contain-intrinsic-block-size",
          "contain-intrinsic-height",
          "contain-intrinsic-inline-size",
          "contain-intrinsic-size",
          "contain-intrinsic-width",
          "container-name",
          "container-type",
          "cursor",
          "cx",
          "cy",
          "d",
          "direction",
          "dominant-baseline",
          "empty-cells",
          "fill",
          "fill-opacity",
          "fill-rule",
          "flood-color",
          "flood-opacity",
          "hyphenate-character",
          "hyphenate-limit-chars",
          "hyphens",
          "image-orientation",
          "image-rendering",
          "initial-letter",
          "inline-size",
          "inset-block-end",
          "inset-block-start",
          "inset-inline-end",
          "inset-inline-start",
          "isolation",
          "lighting-color",
          "line-break",
          "marker-end",
          "marker-mid",
          "marker-start",
          "mask-type",
          "math-depth",
          "math-shift",
          "math-style",
          "mix-blend-mode",
          "object-fit",
          "object-position",
          "object-view-box",
          "offset-distance",
          "offset-path",
          "offset-rotate",
          "orphans",
          "overscroll-behavior-block",
          "overscroll-behavior-inline",
          "paint-order",
          "pointer-events",
          "r",
          "resize",
          "rotate",
          "row-gap",
          "ruby-position",
          "rx",
          "ry",
          "scale",
          "scroll-behavior",
          "scroll-margin",
          "scroll-margin-block-end",
          "scroll-margin-block-start",
          "scroll-margin-inline-end",
          "scroll-margin-inline-start",
          "scroll-padding",
          "scroll-padding-block-end",
          "scroll-padding-block-start",
          "scroll-padding-inline-end",
          "scroll-padding-inline-start",
          "scroll-snap-align",
          "scroll-snap-type",
          "scroll-snap-stop",
          "scrollbar-gutter",
          "shape-image-threshold",
          "shape-margin",
          "shape-outside",
          "shape-rendering",
          "speak",
          "stop-color",
          "stop-opacity",
          "stroke",
          "stroke-dasharray",
          "stroke-dashoffset",
          "stroke-linecap",
          "stroke-linejoin",
          "stroke-miterlimit",
          "stroke-opacity",
          "stroke-width",
          "tab-size",
          "table-layout",
          "touch-action",
          "transition",
          "transition-delay",
          "transition-duration",
          "transition-property",
          "transition-timing-function",
          "translate",
          "unicode-bidi",
          "user-select",
          "vector-effect",
          "vertical-align",
          "view-transition-name",
          "widows",
          "will-change",
          "word-break",
          "writing-mode",
          "x",
          "y",
        ],
      },
    ],
    "order/properties-alphabetical-order": null,
  },
  "overrides": [
    {
      "files": ["*.scss", "**/*.scss"],
      "customSyntax": "postcss-scss",
      "rules": {
        // CSS Override
        "at-rule-no-unknown": null,
        "no-duplicate-selectors": true,
        "no-descending-specificity": null,
        // SCSS rules
        "scss/at-rule-no-unknown": true,
        "scss/at-extend-no-missing-placeholder": [
          true,
          {
            "severity": "warning"
          }
        ],
        "scss/at-function-pattern": [
          "^(-?[a-z][a-z0-9]*)(-[a-z0-9]+)*$",
          {
            "message": "Expected function name to be kebab-case",
          },
        ],
        "scss/at-if-no-null": [
          true,
          {
            "severity": "warning",
            "message": "Equality to null is explicit since null is falsey in Sass, use '@if not $my-var' to check null value",
          },
        ],
        "scss/at-import-partial-extension": "never",
        "scss/at-mixin-argumentless-call-parentheses": "never",
        "scss/at-mixin-pattern": [
          "^(-?[a-z][a-z0-9]*)(-[a-z0-9]+)*$",
          {
            "message": "Expected mixin name to be kebab-case",
          },
        ],
        "scss/dollar-variable-no-missing-interpolation": true,
        "scss/dollar-variable-pattern": [
          "^(-?[a-z][a-z0-9]*)(-[a-z0-9]+)*$",
          {
            message: "Expected variable to be kebab-case",
          },
        ],
        "scss/percent-placeholder-pattern": [
          "^(-?[a-z][a-z0-9]*)(-[a-z0-9]+)*$",
          {
            message: "Expected placeholder to be kebab-case",
          },
        ],
        "scss/double-slash-comment-empty-line-before": null,
        "scss/double-slash-comment-whitespace-inside": "always",
        "scss/comment-no-empty": true,
        "scss/declaration-nested-properties-no-divided-groups": true,
        "scss/function-color-relative": [
          true,
          {
            "severity": "warning",
            "message": "Try to use color functions to manipulate colors with : @use \"sass:color\";",
          },
        ],
        "scss/function-quote-no-quoted-strings-inside": true,
        "scss/function-unquote-no-unquoted-strings-inside": true,
        "scss/map-keys-quotes": [
          "always",
          {
            "severity": "warning",
            "message": "Expected to use quotes on keys in Sass maps.",
          },
        ],
        "scss/media-feature-value-dollar-variable": [
          "always",
          {
            "severity": "warning",
            "message": "Expected to use a $var in media feature value.",
          },
        ],
        "scss/selector-no-redundant-nesting-selector": [
          true,
          {
            "severity": "warning",
            "message": "Expected no redundant nesting selector (&).",
          },
        ],
        "scss/no-duplicate-mixins":[
          true,
          {
            "severity": "warning",
            "message": "Expected no duplicate mixins.",
          },
        ],
      }
    }
  ],
}
